# Generated by Django 6.0.3 on 2026-05-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_logcarrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='is_colaborador',
            field=models.BooleanField(default=False, verbose_name='É Assinante Colaborador?'),
        ),
    ]
