# Generated by Django 6.0.3 on 2026-05-12 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_logcarrinho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logcarrinho',
            options={'verbose_name_plural': 'Logs de Carrinhos'},
        ),
        migrations.RemoveField(
            model_name='evento',
            name='valor_ingresso',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='checkin_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=15),
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantidade_total', models.PositiveIntegerField(help_text='Total de ingressos deste lote')),
                ('quantidade_vendida', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_ingressos', to='app.evento')),
            ],
        ),
        migrations.AddField(
            model_name='inscricao',
            name='ticket_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='app.tickettype'),
        ),
    ]
