# Generated by Django 6.0.3 on 2026-05-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_logcarrinho_options_and_more'),
        ('app', '0003_perfil_is_colaborador'),
    ]

    operations = [
    ]
