# Generated by Django 6.0.3 on 2026-05-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20260512_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='is_colaborador',
        ),
    ]
