# Generated by Django 6.0.3 on 2026-05-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_perfil_cidade_perfil_cnpj_perfil_email_empresarial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='assinatura_paga',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='metodo_pagamento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
