# Generated by Django 6.0.3 on 2026-05-16 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_perfil_assinatura_paga_perfil_metodo_pagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaComprada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_plano', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], max_length=20)),
                ('metodo_pagamento', models.CharField(choices=[('boleto', 'Boleto'), ('cartao', 'Cartão de Crédito'), ('pix', 'Pix')], max_length=20)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('data_vencimento', models.DateTimeField()),
                ('ativa', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
