# Generated by Django 6.0.3 on 2026-05-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_assinaturacomprada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinaturacomprada',
            name='metodo_pagamento',
            field=models.CharField(max_length=20),
        ),
    ]
